# Generated by Django 4.1.5 on 2023-01-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_rename_name_auctionlisting_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='category',
            new_name='brand',
        ),
    ]
