# Generated by Django 4.1.5 on 2023-01-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conent',
            new_name='content',
        ),
    ]
