# Generated by Django 4.1.5 on 2023-01-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_conent_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lisitng',
            new_name='listing',
        ),
    ]
